Extend timeout for DiskLruCacheTest
com.squareup.okhttp.internal.DiskLruCacheTest#rebuildJournalOnRepeatedReadsWithOpenAndClose()
takes more than 30 seconds on low memory devices configured with --compiler-filter=interpret-only,
since dex2oat skips compilations with this option and heavily relies on the runtime interpreter.

com.squareup.okhttp.internal.DiskLruCacheTest#rebuildJournalOnRepeatedReadsWithOpenAndClose FAIL
    java.lang.Exception: test timed out after 30000 milliseconds
    at java.lang.Object.wait(Native Method)
    at java.lang.Thread.join(Thread.java:786)
    at java.lang.Thread.join(Thread.java:744)
    at org.junit.internal.runners.statements.FailOnTimeout.evaluateStatement(FailOnTimeout.java:28)
    at org.junit.internal.runners.statements.FailOnTimeout.evaluate(FailOnTimeout.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)

To avoid spurious failure and provide better compatibility for the test, timeout should be increased.

Change-Id: I393033d428824f518bde10780070bd2c28ef4d15
Signed-off-by: David C. Park <davidc.park@lge.com>